import { Mountain } from './mountain';

export const MOUNTAINS: Mountain[] = [
  { pid: 'D001', name: '中央尖山' },
  { pid: 'D090', name: '志佳陽大山' },
  { pid: 'D080', name: '玉山' },
  { pid: 'D052', name: '雪山北峰'},
  { pid: 'D053', name: '雪山東峰'},
  { pid: 'D054', name: '頭鷹山'},
  { pid: 'D023', name: '丹大山'},
  { pid: 'D011', name: '光頭山'},
  { pid: 'D020', name: '八通關山'},
  { pid: 'D025', name: '六順山'},
  { pid: 'D028', name: '合歡山'},
  { pid: 'D029', name: '合歡山東峰'},
  { pid: 'D088', name: '合歡山西峰'},
  { pid: 'D021', name: '大水窟山'},
  { pid: 'D022', name: '干卓萬山'},
  { pid: 'D033', name: '東巒大山'},
  { pid: 'D032', name: '東郡大山'},
  { pid: 'D042', name: '無雙山'},
  { pid: 'D034', name: '牧山'},
  { pid: 'D083', name: '玉山前峰'},
  { pid: 'D026', name: '玉山北峰'},
  { pid: 'D082', name: '玉山東峰'},
  { pid: 'D081', name: '玉山西峰'},
];
